### ISSUE TITLE
Function to add tags not working

### ISSUE THREAD

**Issue by AllBaconAndEggs** [get-itips/MiscScripts#4]
Hi, firstly, thanks for putting this together. However, I am unable to successfully add Teams tags to users. From what I can tell I am supplying the correct required info into the .csv in a single cell, separated by a semicolon (objectid;userId;tag). I am an owner of the targeted Team, and the tag exists. When I run the function, I am prompted to authenticate with my account, but then I don't get any errors, and nothing seems to happen. Any suggestions? Thanks!

**Comment by get-itips** [comment]
Hello!
Let me test to see if something changed in the backend.

**Comment by get-itips** [comment]
Hello @AllBaconAndEggs 
Finally got some time to test, sorry for late response.
I've managed to use the script without issue, assigning a tag to team members.
What permissions do you have in the tenant?

**Comment by AllBaconAndEggs** [comment]
No worries, thanks for testing. I do have the Teams Administrator role assigned/enabled for my account when I am testing the function. The same account is also an owner in the specified team. Are there any other permissions required?

**Comment by get-itips** [comment]
Let me check specifically with those permissions to see if there is any limitation around that.

**Comment by get-itips** [comment]
@AllBaconAndEggs 
Just in case, are you calling the function with `Add-TagsToUsers`? (Last line of the script)

**Comment by AllBaconAndEggs** [comment]
Hi Andres, I have tried calling the function with `Add-TagsToUsers` and also have tried stepping through the script manually.

**Comment by AllBaconAndEggs** [comment]
Okay, I have resolved the issue... It turned out to simply be me not formatting the header of the .csv file with "objectid;userId;tag". Once I added that, the function worked perfectly. Thank you!

**Comment by get-itips** [comment]
@AllBaconAndEggs Glad to hear!
